version: '3.7'

services:
  news_app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    container_name: news_app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - webnet
    volumes:
      - ./src:/home/node/app/src
    env_file:
      - .env
    init: true
    entrypoint: >
      sh -c "pnpm build &&
             exec node dist/src/main.js"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${APP_PORT}/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
  queue:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    container_name: queue
    networks:
      - webnet
    volumes:
      - ./src:/home/node/app/src
    depends_on:
      - news_app
    env_file:
      - .env
    init: true
    entrypoint: >
      sh -c "echo 'Waiting for charging_app to be ready...' &&
             until curl -s http://news_app:${APP_PORT}/health > /dev/null; do sleep 2; echo 'Waiting...'; done &&
             pnpm run build:queue &&
             exec node dist-queue/src/queue-entrypoint.js"
networks:
  webnet:
    driver: bridge
